In [1]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census



# Census API Keys
from config import (api_key)


#c = Census(api_key, year=2016) #2011 -2017?

In [41]:
years = [2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016]

for i in years:
    cen_data = Census(api_key, year=i)
    census_data = cen_data.acs5.get(("NAME", "B01003_001E", "B08301_001E", "B08301_003E","B08301_004E", "B08301_010E", "B08301_019E", "B08101_041E", "B08015_001E", "B08015_002E", "B08015_003E"), {'for': 'metropolitan statistical area/micropolitan statistical area:*'})
    census_pd = pd.DataFrame(census_data)
    


# Column Reordering
    census_pd = census_pd.rename(columns={"B01003_001E": "Population",
                                      "B08301_001E": "Transit Total",
                                      "B08301_003E": "Transit Solo Auto",
                                      "B08301_004E": "Transit Carpool",
                                      "B08301_010E": "Transit Public Transp.",
                                      "B08301_019E": "Transit Walked",
                                      "B08101_041E": "Transit Other",
                                      "NAME": "Name", 
                                      "B08015_001E": "Vehicles",
                                      "B08015_002E": "Vehicles (M)",
                                      "B08015_003E": "Vehicles (F)",
                                      "metropolitan statistical area/micropolitan statistical area": "Metro Code"})
    
    
    # Converting object to floats and then calculating % for transit times
    for j in range(0,10):
        census_pd.iloc[:,j] = pd.to_numeric(census_pd.iloc[:,j] )
    
    census_pd['Year'] = i
    census_pd['New Transit Total'] = (census_pd['Transit Solo Auto']) + (census_pd['Transit Carpool']) + (census_pd['Transit Public Transp.']) + (census_pd['Transit Walked']) + (census_pd['Transit Other'])
    #new transit total calculates a new value for the total transit since there seems to be some discrepancies with the total that is given
    
    census_pd['Solo Auto %'] = round(100*census_pd["Transit Solo Auto"]/census_pd['New Transit Total'],1)
    census_pd['Carpool %'] = round(100*census_pd["Transit Carpool"]/census_pd['New Transit Total'],1)
    census_pd['Public Transp. %'] = round(100*census_pd["Transit Public Transp."]/census_pd['New Transit Total'],1)
    census_pd['Walked %'] = round(100*census_pd["Transit Walked"]/census_pd['New Transit Total'],1)
    census_pd['Other %'] = round(100*census_pd["Transit Other"]/census_pd['New Transit Total'],1)
    
    if (i == years[0]):
        austin_data = census_pd[census_pd['Metro Code'] == '12420']
        nash_data = census_pd[census_pd['Metro Code'] == '34980']
        dallas_data = census_pd[census_pd['Metro Code'] == '19100']
        atl_data = census_pd[census_pd['Metro Code'] == '12060']
    else:
        austin_data = austin_data.append(census_pd[census_pd['Metro Code'] == '12420'])
        nash_data = nash_data.append(census_pd[census_pd['Metro Code'] == '34980'])
        dallas_data = dallas_data.append(census_pd[census_pd['Metro Code'] == '19100'])
        atl_data = atl_data.append(census_pd[census_pd['Metro Code'] == '12060'])
#austin 12420
#atl 12060
#dallas 19100
#nash 34980
    
     

axiscols = ['Name', 'Year', 'Population', 'Vehicles', 'Vehicles (M)', 'Vehicles (F)',
        'Transit Solo Auto','Transit Carpool', 'Transit Public Transp.', 'Transit Walked',
         'Transit Other', 'Transit Total',
      'New Transit Total', 'Solo Auto %', 'Carpool %',
       'Public Transp. %', 'Walked %', 'Other %']

In [42]:

atl_data = atl_data[axiscols]
atl_data.iloc[:,2:12] = atl_data.iloc[:,2:12].round().astype(int)
atl_data = atl_data.set_index("Name")
atl_data.to_csv("Atlanta_Census.csv")
atl_data.head()

,Year,Population,Vehicles,Vehicles (M),Vehicles (F),Transit Solo Auto,Transit Carpool,Transit Public Transp.,Transit Walked,Transit Other,Transit Total,New Transit Total,Solo Auto %,Carpool %,Public Transp. %,Walked %,Other %
Name,,,,,,,,,,,,,,,,,
"Atlanta-Sandy Springs-Marietta, GA Metro Area",2009,5238994,2052480,1090620,961865,1932100,271768,90002,34299,40085,2494475,2368254.0,81.6,11.5,3.8,1.4,1.7
"Atlanta-Sandy Springs-Marietta, GA Metro Area",2010,5125113,1997095,1045905,951190,1881294,261013,81646,32150,41000,2426787,2297103.0,81.9,11.4,3.6,1.4,1.8
"Atlanta-Sandy Springs-Marietta, GA Metro Area",2011,5213854,2003545,1042565,960980,1887598,260845,79623,32523,40263,2434425,2300852.0,82.0,11.3,3.5,1.4,1.7
"Atlanta-Sandy Springs-Marietta, GA Metro Area",2012,5291701,2008995,1045940,963055,1893486,260512,77953,32535,37735,2440294,2302221.0,82.2,11.3,3.4,1.4,1.6
"Atlanta-Sandy Springs-Roswell, GA Metro Area",2013,5379176,2013310,1045965,967345,1900270,254574,76142,33625,36652,2440839,2301263.0,82.6,11.1,3.3,1.5,1.6

In [43]:
dallas_data = dallas_data[axiscols]
dallas_data.iloc[:,2:12] = dallas_data.iloc[:,2:12].round().astype(int)
dallas_data = dallas_data.set_index("Name")
dallas_data.to_csv("Dallas_Census.csv")
dallas_data.head()

,Year,Population,Vehicles,Vehicles (M),Vehicles (F),Transit Solo Auto,Transit Carpool,Transit Public Transp.,Transit Walked,Transit Other,Transit Total,New Transit Total,Solo Auto %,Carpool %,Public Transp. %,Walked %,Other %
Name,,,,,,,,,,,,,,,,,
"Dallas-Fort Worth-Arlington, TX Metro Area",2009,6144234,2511105,1406040,1105065,2360732,336628,48042,40414,42864,2945976,2828680.0,83.5,11.9,1.7,1.4,1.5
"Dallas-Fort Worth-Arlington, TX Metro Area",2010,6154265,2517930,1376365,1141565,2374424,319784,45941,39040,43319,2945952,2822508.0,84.1,11.3,1.6,1.4,1.5
"Dallas-Fort Worth-Arlington, TX Metro Area",2011,6280597,2567560,1397920,1169640,2425795,315037,45290,36490,43947,2996020,2866559.0,84.6,11.0,1.6,1.3,1.5
"Dallas-Fort Worth-Arlington, TX Metro Area",2012,6400781,2604735,1415970,1188765,2461179,318559,45499,37051,45459,3043357,2907747.0,84.6,11.0,1.6,1.3,1.6
"Dallas-Fort Worth-Arlington, TX Metro Area",2013,6575833,2665690,1447085,1218605,2524016,314756,44105,37697,47197,3112236,2967771.0,85.0,10.6,1.5,1.3,1.6

In [44]:
austin_data = austin_data[axiscols]
austin_data.iloc[:,2:12] = austin_data.iloc[:,2:12].round().astype(int)
austin_data = austin_data.set_index("Name")
austin_data.to_csv("Austin_Census.csv")
austin_data.head()

,Year,Population,Vehicles,Vehicles (M),Vehicles (F),Transit Solo Auto,Transit Carpool,Transit Public Transp.,Transit Walked,Transit Other,Transit Total,New Transit Total,Solo Auto %,Carpool %,Public Transp. %,Walked %,Other %
Name,,,,,,,,,,,,,,,,,
"Austin-Round Rock, TX Metro Area",2009,1589393,652425,364205,288220,607740,100696,22434,13280,21618,810017,765768.0,79.4,13.1,2.9,1.7,2.8
"Austin-Round Rock-San Marcos, TX Metro Area",2010,1627571,662555,361790,300765,618506,98933,21479,13925,21248,823119,774091.0,79.9,12.8,2.8,1.8,2.7
"Austin-Round Rock-San Marcos, TX Metro Area",2011,1681167,677430,367865,309560,633174,99289,21987,14628,22131,845297,791209.0,80.0,12.5,2.8,1.8,2.8
"Austin-Round Rock-San Marcos, TX Metro Area",2012,1731777,694125,375025,319100,650154,97904,22229,15916,23316,866411,809519.0,80.3,12.1,2.7,2.0,2.9
"Austin-Round Rock, TX Metro Area",2013,1782032,718205,386880,331330,675639,94559,21640,16326,22104,890006,830268.0,81.4,11.4,2.6,2.0,2.7

In [45]:
nash_data = nash_data[axiscols]
nash_data.iloc[:,2:12] = nash_data.iloc[:,2:12].round().astype(int)
nash_data = nash_data.set_index("Name")
nash_data.to_csv("Nashville_Census.csv")
nash_data.head()

,Year,Population,Vehicles,Vehicles (M),Vehicles (F),Transit Solo Auto,Transit Carpool,Transit Public Transp.,Transit Walked,Transit Other,Transit Total,New Transit Total,Solo Auto %,Carpool %,Public Transp. %,Walked %,Other %
Name,,,,,,,,,,,,,,,,,
"Nashville-Davidson--Murfreesboro--Franklin, TN Metro Area",2009,1520649,639955,342755,297200,605050,76428,7415,9617,9280,739294,707790.0,85.5,10.8,1.0,1.4,1.3
"Nashville-Davidson--Murfreesboro--Franklin, TN Metro Area",2010,1541541,639550,339775,299770,604037,77509,7665,9471,9048,740734,707730.0,85.3,11.0,1.1,1.3,1.3
"Nashville-Davidson--Murfreesboro--Franklin, TN Metro Area",2011,1569470,644255,340080,304180,608511,78218,8678,9290,8776,748011,713473.0,85.3,11.0,1.2,1.3,1.2
"Nashville-Davidson--Murfreesboro--Franklin, TN Metro Area",2012,1595454,654430,344915,309515,618647,78511,8643,9436,8565,758698,723802.0,85.5,10.8,1.2,1.3,1.2
"Nashville-Davidson--Murfreesboro--Franklin, TN Metro Area",2013,1702603,695500,364250,331250,659340,79521,8872,10121,8787,802808,766641.0,86.0,10.4,1.2,1.3,1.1